version: '3'

networks:
  lan:
  wan:

services:
  web:
    image: "nginx:stable-alpine"
    ports:
      - "8080:80"
    volumes:
      - ./web/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./web/static:/var/www:ro
    command: [nginx-debug, '-g', 'daemon off;']
    networks:
      - wan
      - lan

  backend:
    build: 
      context: ./server
      dockerfile: Dockerfile
    networks:
      - lan